services:
  - type: web
    name: ai-business-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: aibusiness-db
          property: connectionString
  - type: static
    name: ai-business-frontend
    buildCommand: cd front_end && npm install && npm run build
    staticPublishPath: front_end/dist

databases:
  - name: aibusiness-db
    plan: free
