# Generated by Django 5.1.7 on 2025-04-23 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Default Assessment", max_length=255),
                ),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(max_length=254)),
                ("full_name", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("industry_niche", models.CharField(max_length=255)),
                (
                    "years_in_business",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "number_of_employees",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "annual_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("geographic_locations", models.TextField(blank=True)),
                ("main_products", models.TextField()),
                ("current_performance", models.TextField()),
                ("biggest_challenges", models.TextField()),
                ("business_vision", models.TextField()),
                ("primary_goals", models.TextField()),
                ("success_indicators", models.TextField(blank=True)),
                ("market_research", models.TextField()),
                ("target_customers", models.TextField()),
                ("competitors", models.TextField()),
                ("current_brand_identity", models.TextField()),
                ("brand_values", models.TextField()),
                ("brand_assets", models.TextField()),
                ("organizational_structure", models.TextField()),
                ("operations_management", models.TextField()),
                ("operational_challenges", models.TextField()),
                ("business_plan", models.TextField()),
                ("business_goals", models.TextField()),
                ("progress_tracking", models.TextField()),
                ("brand_identity", models.TextField(blank=True, null=True)),
                ("business_description", models.TextField(blank=True, null=True)),
                ("main_competitors", models.TextField(blank=True, null=True)),
                ("specific_outcomes", models.TextField(blank=True, null=True)),
                ("additional_info", models.TextField(blank=True)),
                ("specific_questions", models.TextField(blank=True)),
                ("analysis_results", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("openai_api_key", models.CharField(blank=True, max_length=255)),
                (
                    "openai_model",
                    models.CharField(default="gpt-3.5-turbo", max_length=50),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("market_position", "market_position"),
                            ("growth_potential", "growth_potential"),
                            ("swot", "swot"),
                        ],
                        default="market_position",
                        max_length=50,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaires",
                        to="assessment.businessassessment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaires",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("analysis", models.TextField()),
                ("product_suggestions", models.TextField()),
                ("growth_potential", models.TextField(blank=True, null=True)),
                ("operation_insight", models.TextField(blank=True, null=True)),
                ("strategic_recommendation", models.TextField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.businessassessment",
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.questionnaire",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "company",
                    models.CharField(default="Default Company", max_length=255),
                ),
                ("website", models.URLField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
