# Generated by Django 5.1.7 on 2025-04-20 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="assessment.businessassessment",
            ),
        ),
        migrations.RenameField(
            model_name="questionnaire",
            old_name="business_assessment",
            new_name="assessment",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="business_vision",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="competitive_advantages",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="current_challenges",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="main_competitors",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="main_products_services",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="market_research_conducted",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="number_of_employees",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="primary_business_goals",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="target_customer",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="years_in_business",
        ),
        migrations.AddField(
            model_name="businessassessment",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="businessassessment",
            name="name",
            field=models.CharField(default="Default Assessment", max_length=255),
        ),
        migrations.AddField(
            model_name="businessassessment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="businessassessment",
            name="annual_revenue",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="businessassessment",
            name="number_of_employees",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="businessassessment",
            name="years_in_business",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="company",
            field=models.CharField(default="Default Company", max_length=255),
        ),
        migrations.DeleteModel(
            name="Assessment",
        ),
    ]
